name:
  dousheng-backend
port:
  8084

mysql:
  host: 81.70.28.187
  port: 3306
  user: root
  password: admin
  dbname: dousheng
  max_open_conns: 200
  max_idle_conns: 50


redis:
  host: 81.70.28.187
  port: 6379
  password:
  db: 0
  pool_size: 100

oss:
  end_point: oss-cn-hangzhou.aliyuncs.com
  access_key_id: LTAI5tJrnNJk1NuHbCsBZcSa
  access_key_secret: wNDLd19m3UFCwwmUUABEO4us3QEWF2
  bucket_name: byte-dance-zh
  suffer_url: http://byte-dance-zh.oss-cn-hangzhou.aliyuncs.com/
cover_in_server:
  D:\photos
ffmpeg_path:
  E:\program_Environment\school\Tools\ffmpeg\bin\ffmpeg.exe



